"""expand shopify mirror fields add field visibility user column prefs

Revision ID: 13fbc4d4a942
Revises: 2749ced6a116
Create Date: 2026-05-25 06:25:58.427674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '13fbc4d4a942'
down_revision: Union[str, None] = '2749ced6a116'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('field_visibility_settings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('shop_id', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('field_key', sa.String(), nullable=False),
    sa.Column('field_label', sa.String(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_id', 'entity_type', 'field_key', name='uq_field_visibility')
    )
    op.create_index(op.f('ix_field_visibility_settings_entity_type'), 'field_visibility_settings', ['entity_type'], unique=False)
    op.create_index(op.f('ix_field_visibility_settings_field_key'), 'field_visibility_settings', ['field_key'], unique=False)
    op.create_index(op.f('ix_field_visibility_settings_shop_id'), 'field_visibility_settings', ['shop_id'], unique=False)
    op.create_table('user_column_prefs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('column_order', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'entity_type', name='uq_user_column_pref')
    )
    op.create_index(op.f('ix_user_column_prefs_entity_type'), 'user_column_prefs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_user_column_prefs_user_id'), 'user_column_prefs', ['user_id'], unique=False)
    op.add_column('customers', sa.Column('admin_graphql_api_id', sa.String(), nullable=True))
    op.add_column('customers', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('customers', sa.Column('currency', sa.String(length=10), nullable=True))
    op.add_column('customers', sa.Column('accepts_marketing', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('customers', sa.Column('accepts_marketing_updated_at', sa.String(), nullable=True))
    op.add_column('customers', sa.Column('marketing_opt_in_level', sa.String(), nullable=True))
    op.add_column('customers', sa.Column('email_marketing_consent', sa.JSON(), nullable=True))
    op.add_column('customers', sa.Column('sms_marketing_consent', sa.JSON(), nullable=True))
    op.add_column('customers', sa.Column('state', sa.String(), nullable=True))
    op.add_column('customers', sa.Column('verified_email', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('customers', sa.Column('tax_exempt', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('customers', sa.Column('tax_exemptions', sa.JSON(), nullable=True))
    op.add_column('customers', sa.Column('orders_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('customers', sa.Column('total_spent', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('customers', sa.Column('last_order_id', sa.String(), nullable=True))
    op.add_column('customers', sa.Column('last_order_name', sa.String(), nullable=True))
    op.add_column('customers', sa.Column('note', sa.Text(), nullable=True))
    op.add_column('customers', sa.Column('tags', sa.JSON(), nullable=True))
    op.add_column('customers', sa.Column('default_address', sa.JSON(), nullable=True))
    op.add_column('customers', sa.Column('shopify_created_at', sa.String(), nullable=True))
    op.add_column('customers', sa.Column('shopify_updated_at', sa.String(), nullable=True))
    op.create_index(op.f('ix_customers_phone'), 'customers', ['phone'], unique=False)
    op.add_column('line_items', sa.Column('admin_graphql_api_id', sa.String(), nullable=True))
    op.add_column('line_items', sa.Column('shopify_product_id', sa.String(), nullable=True))
    op.add_column('line_items', sa.Column('shopify_variant_id', sa.String(), nullable=True))
    op.add_column('line_items', sa.Column('name', sa.String(), nullable=True))
    op.add_column('line_items', sa.Column('title', sa.String(), nullable=True))
    op.add_column('line_items', sa.Column('vendor', sa.String(), nullable=True))
    op.add_column('line_items', sa.Column('product_type', sa.String(), nullable=True))
    op.add_column('line_items', sa.Column('fulfillable_quantity', sa.Integer(), server_default='0', nullable=False))
    op.add_column('line_items', sa.Column('compare_at_price', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('line_items', sa.Column('total_discount', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('line_items', sa.Column('pre_tax_price', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('line_items', sa.Column('price_set', sa.JSON(), nullable=True))
    op.add_column('line_items', sa.Column('total_discount_set', sa.JSON(), nullable=True))
    op.add_column('line_items', sa.Column('grams', sa.Integer(), nullable=True))
    op.add_column('line_items', sa.Column('fulfillment_service', sa.String(), nullable=True))
    op.add_column('line_items', sa.Column('fulfillment_status', sa.String(), nullable=True))
    op.add_column('line_items', sa.Column('variant_inventory_management', sa.String(), nullable=True))
    op.add_column('line_items', sa.Column('requires_shipping', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('line_items', sa.Column('taxable', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('line_items', sa.Column('gift_card', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('line_items', sa.Column('tax_lines', sa.JSON(), nullable=True))
    op.add_column('line_items', sa.Column('discount_allocations', sa.JSON(), nullable=True))
    op.add_column('line_items', sa.Column('duties', sa.JSON(), nullable=True))
    op.add_column('line_items', sa.Column('properties', sa.JSON(), nullable=True))
    op.alter_column('line_items', 'price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True)
    op.create_index(op.f('ix_line_items_shopify_line_item_id'), 'line_items', ['shopify_line_item_id'], unique=False)
    op.create_index(op.f('ix_line_items_shopify_product_id'), 'line_items', ['shopify_product_id'], unique=False)
    op.create_index(op.f('ix_line_items_shopify_variant_id'), 'line_items', ['shopify_variant_id'], unique=False)
    op.add_column('orders', sa.Column('admin_graphql_api_id', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('order_status_url', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('confirmation_number', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('cart_token', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('checkout_token', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('checkout_id', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('cancel_reason', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('cancelled_at', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('closed_at', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('processed_at', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('presentment_currency', sa.String(length=10), nullable=True))
    op.add_column('orders', sa.Column('subtotal_price', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('orders', sa.Column('total_tax', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('orders', sa.Column('total_discounts', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('orders', sa.Column('total_line_items_price', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('orders', sa.Column('total_outstanding', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('orders', sa.Column('total_tip_received', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('orders', sa.Column('total_weight', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('taxes_included', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('orders', sa.Column('confirmed', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('orders', sa.Column('test', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('orders', sa.Column('payment_gateway', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('payment_gateway_names', sa.JSON(), nullable=True))
    op.add_column('orders', sa.Column('processing_method', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('email', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('customer_locale', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('buyer_accepts_marketing', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('orders', sa.Column('billing_address', sa.JSON(), nullable=True))
    op.add_column('orders', sa.Column('shipping_lines', sa.JSON(), nullable=True))
    op.add_column('orders', sa.Column('discount_codes', sa.JSON(), nullable=True))
    op.add_column('orders', sa.Column('discount_applications', sa.JSON(), nullable=True))
    op.add_column('orders', sa.Column('note_attributes', sa.JSON(), nullable=True))
    op.add_column('orders', sa.Column('source_name', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('source_identifier', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('source_url', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('referring_site', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('landing_site', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('po_number', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('app_id', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('browser_ip', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('client_details', sa.JSON(), nullable=True))
    op.add_column('orders', sa.Column('risk_level', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('location_id', sa.String(), nullable=True))
    op.alter_column('orders', 'currency',
               existing_type=sa.VARCHAR(length=3),
               type_=sa.String(length=10),
               existing_nullable=True)
    op.alter_column('orders', 'total_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True)
    op.alter_column('orders', 'note',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.create_index(op.f('ix_orders_email'), 'orders', ['email'], unique=False)
    op.create_index(op.f('ix_orders_financial_status'), 'orders', ['financial_status'], unique=False)
    op.add_column('products', sa.Column('admin_graphql_api_id', sa.String(), nullable=True))
    op.add_column('products', sa.Column('status', sa.String(), nullable=True))
    op.add_column('products', sa.Column('tags', sa.JSON(), nullable=True))
    op.add_column('products', sa.Column('body_html', sa.Text(), nullable=True))
    op.add_column('products', sa.Column('template_suffix', sa.String(), nullable=True))
    op.add_column('products', sa.Column('images', sa.JSON(), nullable=True))
    op.add_column('products', sa.Column('image', sa.JSON(), nullable=True))
    op.add_column('products', sa.Column('options', sa.JSON(), nullable=True))
    op.add_column('products', sa.Column('published_at', sa.String(), nullable=True))
    op.add_column('products', sa.Column('published_scope', sa.String(), nullable=True))
    op.create_index(op.f('ix_products_product_type'), 'products', ['product_type'], unique=False)
    op.create_index(op.f('ix_products_status'), 'products', ['status'], unique=False)
    op.create_index(op.f('ix_products_vendor'), 'products', ['vendor'], unique=False)
    op.add_column('variants', sa.Column('admin_graphql_api_id', sa.String(), nullable=True))
    op.add_column('variants', sa.Column('shopify_inventory_item_id', sa.String(), nullable=True))
    op.add_column('variants', sa.Column('barcode', sa.String(), nullable=True))
    op.add_column('variants', sa.Column('position', sa.Integer(), nullable=True))
    op.add_column('variants', sa.Column('option1', sa.String(), nullable=True))
    op.add_column('variants', sa.Column('option2', sa.String(), nullable=True))
    op.add_column('variants', sa.Column('option3', sa.String(), nullable=True))
    op.add_column('variants', sa.Column('compare_at_price', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('variants', sa.Column('grams', sa.Integer(), nullable=True))
    op.add_column('variants', sa.Column('weight', sa.Numeric(precision=10, scale=4), nullable=True))
    op.add_column('variants', sa.Column('weight_unit', sa.String(length=10), nullable=True))
    op.add_column('variants', sa.Column('old_inventory_quantity', sa.Integer(), nullable=True))
    op.add_column('variants', sa.Column('inventory_management', sa.String(), nullable=True))
    op.add_column('variants', sa.Column('inventory_policy', sa.String(), nullable=True))
    op.add_column('variants', sa.Column('fulfillment_service', sa.String(), nullable=True))
    op.add_column('variants', sa.Column('requires_shipping', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('variants', sa.Column('taxable', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('variants', sa.Column('tax_code', sa.String(), nullable=True))
    op.add_column('variants', sa.Column('image_id', sa.String(), nullable=True))
    op.add_column('variants', sa.Column('image', sa.JSON(), nullable=True))
    op.execute('ALTER TABLE variants ALTER COLUMN price TYPE NUMERIC(12,2) USING price::numeric(12,2)')
    op.execute('ALTER TABLE variants ALTER COLUMN inventory_quantity TYPE INTEGER USING inventory_quantity::integer')
    op.create_index(op.f('ix_variants_barcode'), 'variants', ['barcode'], unique=False)
    op.create_index(op.f('ix_variants_shopify_inventory_item_id'), 'variants', ['shopify_inventory_item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_variants_shopify_inventory_item_id'), table_name='variants')
    op.drop_index(op.f('ix_variants_barcode'), table_name='variants')
    op.alter_column('variants', 'inventory_quantity',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('variants', 'price',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('variants', 'image')
    op.drop_column('variants', 'image_id')
    op.drop_column('variants', 'tax_code')
    op.drop_column('variants', 'taxable')
    op.drop_column('variants', 'requires_shipping')
    op.drop_column('variants', 'fulfillment_service')
    op.drop_column('variants', 'inventory_policy')
    op.drop_column('variants', 'inventory_management')
    op.drop_column('variants', 'old_inventory_quantity')
    op.drop_column('variants', 'weight_unit')
    op.drop_column('variants', 'weight')
    op.drop_column('variants', 'grams')
    op.drop_column('variants', 'compare_at_price')
    op.drop_column('variants', 'option3')
    op.drop_column('variants', 'option2')
    op.drop_column('variants', 'option1')
    op.drop_column('variants', 'position')
    op.drop_column('variants', 'barcode')
    op.drop_column('variants', 'shopify_inventory_item_id')
    op.drop_column('variants', 'admin_graphql_api_id')
    op.drop_index(op.f('ix_products_vendor'), table_name='products')
    op.drop_index(op.f('ix_products_status'), table_name='products')
    op.drop_index(op.f('ix_products_product_type'), table_name='products')
    op.drop_column('products', 'published_scope')
    op.drop_column('products', 'published_at')
    op.drop_column('products', 'options')
    op.drop_column('products', 'image')
    op.drop_column('products', 'images')
    op.drop_column('products', 'template_suffix')
    op.drop_column('products', 'body_html')
    op.drop_column('products', 'tags')
    op.drop_column('products', 'status')
    op.drop_column('products', 'admin_graphql_api_id')
    op.drop_index(op.f('ix_orders_financial_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_email'), table_name='orders')
    op.alter_column('orders', 'note',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('orders', 'total_price',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('orders', 'currency',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=3),
               existing_nullable=True)
    op.drop_column('orders', 'location_id')
    op.drop_column('orders', 'risk_level')
    op.drop_column('orders', 'client_details')
    op.drop_column('orders', 'browser_ip')
    op.drop_column('orders', 'app_id')
    op.drop_column('orders', 'po_number')
    op.drop_column('orders', 'landing_site')
    op.drop_column('orders', 'referring_site')
    op.drop_column('orders', 'source_url')
    op.drop_column('orders', 'source_identifier')
    op.drop_column('orders', 'source_name')
    op.drop_column('orders', 'note_attributes')
    op.drop_column('orders', 'discount_applications')
    op.drop_column('orders', 'discount_codes')
    op.drop_column('orders', 'shipping_lines')
    op.drop_column('orders', 'billing_address')
    op.drop_column('orders', 'buyer_accepts_marketing')
    op.drop_column('orders', 'customer_locale')
    op.drop_column('orders', 'phone')
    op.drop_column('orders', 'email')
    op.drop_column('orders', 'processing_method')
    op.drop_column('orders', 'payment_gateway_names')
    op.drop_column('orders', 'payment_gateway')
    op.drop_column('orders', 'test')
    op.drop_column('orders', 'confirmed')
    op.drop_column('orders', 'taxes_included')
    op.drop_column('orders', 'total_weight')
    op.drop_column('orders', 'total_tip_received')
    op.drop_column('orders', 'total_outstanding')
    op.drop_column('orders', 'total_line_items_price')
    op.drop_column('orders', 'total_discounts')
    op.drop_column('orders', 'total_tax')
    op.drop_column('orders', 'subtotal_price')
    op.drop_column('orders', 'presentment_currency')
    op.drop_column('orders', 'processed_at')
    op.drop_column('orders', 'closed_at')
    op.drop_column('orders', 'cancelled_at')
    op.drop_column('orders', 'cancel_reason')
    op.drop_column('orders', 'checkout_id')
    op.drop_column('orders', 'checkout_token')
    op.drop_column('orders', 'cart_token')
    op.drop_column('orders', 'confirmation_number')
    op.drop_column('orders', 'order_status_url')
    op.drop_column('orders', 'admin_graphql_api_id')
    op.drop_index(op.f('ix_line_items_shopify_variant_id'), table_name='line_items')
    op.drop_index(op.f('ix_line_items_shopify_product_id'), table_name='line_items')
    op.drop_index(op.f('ix_line_items_shopify_line_item_id'), table_name='line_items')
    op.alter_column('line_items', 'price',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.drop_column('line_items', 'properties')
    op.drop_column('line_items', 'duties')
    op.drop_column('line_items', 'discount_allocations')
    op.drop_column('line_items', 'tax_lines')
    op.drop_column('line_items', 'gift_card')
    op.drop_column('line_items', 'taxable')
    op.drop_column('line_items', 'requires_shipping')
    op.drop_column('line_items', 'variant_inventory_management')
    op.drop_column('line_items', 'fulfillment_status')
    op.drop_column('line_items', 'fulfillment_service')
    op.drop_column('line_items', 'grams')
    op.drop_column('line_items', 'total_discount_set')
    op.drop_column('line_items', 'price_set')
    op.drop_column('line_items', 'pre_tax_price')
    op.drop_column('line_items', 'total_discount')
    op.drop_column('line_items', 'compare_at_price')
    op.drop_column('line_items', 'fulfillable_quantity')
    op.drop_column('line_items', 'product_type')
    op.drop_column('line_items', 'vendor')
    op.drop_column('line_items', 'title')
    op.drop_column('line_items', 'name')
    op.drop_column('line_items', 'shopify_variant_id')
    op.drop_column('line_items', 'shopify_product_id')
    op.drop_column('line_items', 'admin_graphql_api_id')
    op.drop_index(op.f('ix_customers_phone'), table_name='customers')
    op.drop_column('customers', 'shopify_updated_at')
    op.drop_column('customers', 'shopify_created_at')
    op.drop_column('customers', 'default_address')
    op.drop_column('customers', 'tags')
    op.drop_column('customers', 'note')
    op.drop_column('customers', 'last_order_name')
    op.drop_column('customers', 'last_order_id')
    op.drop_column('customers', 'total_spent')
    op.drop_column('customers', 'orders_count')
    op.drop_column('customers', 'tax_exemptions')
    op.drop_column('customers', 'tax_exempt')
    op.drop_column('customers', 'verified_email')
    op.drop_column('customers', 'state')
    op.drop_column('customers', 'sms_marketing_consent')
    op.drop_column('customers', 'email_marketing_consent')
    op.drop_column('customers', 'marketing_opt_in_level')
    op.drop_column('customers', 'accepts_marketing_updated_at')
    op.drop_column('customers', 'accepts_marketing')
    op.drop_column('customers', 'currency')
    op.drop_column('customers', 'phone')
    op.drop_column('customers', 'admin_graphql_api_id')
    op.drop_index(op.f('ix_user_column_prefs_user_id'), table_name='user_column_prefs')
    op.drop_index(op.f('ix_user_column_prefs_entity_type'), table_name='user_column_prefs')
    op.drop_table('user_column_prefs')
    op.drop_index(op.f('ix_field_visibility_settings_shop_id'), table_name='field_visibility_settings')
    op.drop_index(op.f('ix_field_visibility_settings_field_key'), table_name='field_visibility_settings')
    op.drop_index(op.f('ix_field_visibility_settings_entity_type'), table_name='field_visibility_settings')
    op.drop_table('field_visibility_settings')
    # ### end Alembic commands ###
